---
- name: Checking if Rustup is already installed
  stat:
    path: "{{ rustup_completion }}"
  register: rustup_installed
  become: true

- name: Installing Rustup package manager
  block:
  - name: Creating temporary directory
    file:
      path: "{{ rustup_tmp }}"
      state: directory

  - name: Downloading installation script
    get_url:
      url: "{{ rustup_url }}"
      dest: "{{ rustup_tmp }}/install.sh"
      checksum: "{{ rustup_checksum }}"
      mode: 0777

  - name: Installing Rustup
    command: sh -c "{{ rustup_tmp }}/install.sh -y"
    register: install_result
    changed_when: "install_result.rc == 0"

  - name: Removing temporary directory
    file:
      path: "{{ rustup_tmp }}"
      state: absent

  - name: Installing shell completion for Rust
    block:
    - name: Creating directory
      file:
        path: /etc/bash_completion.d
        state: directory
        recurse: yes

    - name: Add shell completion file
      shell: "{{ cargo_path }}/bin/rustup completions bash > {{ rustup_completion }}"
      args:
        creates: /etc/bash_completion.d/rustup_completion

    become: true

  when: not rustup_installed.stat.exists

- name: Installing dependencies
  apt:
    name: "{{ rust_packages }}"
    state: present
  become: true

- name: Installing Cargo crates
  command: cargo install {{ item }}
  loop: "{{ cargo_crates }}"
  register: crate_status
  changed_when: "'already installed' not in crate_status.stderr"
