---
- name: Set up Fedora Workstation - the @S1SYPHOS way.
  hosts: local
  roles:
    # BASE
    - system
    - packages
    - keybindings

    # FUNCTION
    # TODO: Migrate to dotbot 
    # - dotfiles
    - php
    - git
    - ruby
    - nodejs
    - python
    - containerization

    # FORM
    - gnome
    - themes
    - shell_extensions

  pre_tasks:
    - name: Update Packages
      dnf:
        name: "*"
        state: latest
      become: true

