---
- name: ~ is where ur . files r
  block:
    - name: Install requisite Packages
      dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ dotfile_packages }}"
      become: yes

    - name: Clone dotfiles
      git:
        repo: git@github.com:S1SYPHOS/dotfiles.git
        dest: "{{ dotfile_path }}"
      ignore_errors: yes

    - name: Symlink all Dotfiles
      command: "{{ dotfile_path }}/install.sh"
      changed_when: false

  tags:
    - base
    - configuration
