---
- name: Checking if dotfiles already exist
  stat:
    path: "{{ dotfile_path }}"
  register: dotfiles_cloned

- name: ~ is where ur . files r
  block:
    - name: Cloning dotfiles
      git:
        repo: git@github.com:S1SYPHOS/dotfiles.git
        dest: "{{ dotfile_path }}"
      ignore_errors: true
      become: true

    - name: Symlinking dotfiles
      command: "{{ dotfile_path }}/install.sh"
      changed_when: false

  when: not dotfiles_cloned.stat.exists
