---
- name: Installing NodeJS, NPM & modules
  block:
  - name: Installing NodeJS & NPM
    apt:
      name: "{{ node_packages }}"
      state: present
    become: true

  - name: Creating directories
    file:
      path: "{{ node_modules_path }}/{{ item }}"
      state: directory
    loop:
      - bin
      - lib

  - name: Installing Node modules
    npm:
      name: "{{ item }}"
      state: present
      global: true
    loop: "{{ node_modules }}"

  tags:
    - node
