---
- name: Setting up containerization
  block:
    - name: Installing container tools
      apt:
        name: "{{ container_tools }}"
        state: present
      become: true

    - name: Creating directories
      file:
        path: "{{ oci_conf_path }}"
        state: directory

    - name: Copying configuration files
      template:
        src: "{{ item }}.j2"
        dest: "{{ oci_conf_path }}/{{ item }}"
      loop:
        - libpod.conf
        - storage.conf

  tags:
    - containerization

- name: Setting up virtualization
  block:
    - name: Adding Hashicorp repository
      copy:
        src: "{{ role_path }}/files/hashicorp.list"
        dest: /etc/apt/sources.list.d/
        owner: root
        group: root
        mode: 0644

    - name: Adding Hashicorp signing key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present


    - name: Installing virtualization tools
      apt:
        name: "{{ vm_tools }}"
        state: present
        update_cache: true

    - name: Starting libvirt daemon
      service:
        name: libvirtd
        state: started

    - name: Enabling libvirt daemon
      service:
        name: libvirtd
        enabled: true

    - name: Installing Vagrant plugins
      command: /usr/bin/vagrant plugin install {{ item | quote }}
      loop: "{{ vagrant_plugins }}"
      become: false

  become: true
  tags:
    - virtualization
