---
- name: Installing PIP & packages
  block:
  - name: Installing PIP
    apt:
      name: "{{ python_packages }}"
      state: present
    become: true

  - name: Creating directories
    file:
      path: "{{ pip_packages_path }}"
      state: directory

  - name: Installing PIP Packages
    pip:
      name: "{{ item }}"
      state: present
    loop: "{{ pip_packages }}"
