---
- name: Stopping & disabling bluetooth
  block:
  - name: Stopping bluetooth service
    service:
      name: bluetooth
      state: stopped
  - name: Disabling bluetooth service
    service:
      name: bluetooth
      enabled: no

  become: true
