---
- name: Setting hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname != ""
  become: true

- name: Include Bluetooth
  include: bluetooth.yml


##
# POWER MANAGEMENT
##

- name: Include TLP
  include: tlp.yml
