---
- name: Enabling advanced power management
  block:
  - name: Installing TLP
    apt:
      name: tlp
      state: present

  - name: Starting TLP
    service:
      name: tlp
      state: started

  - name: Enabling TLP
    service:
      name: tlp
      enabled: true

  become: true

  tags:
    - power
