---
- name: Enabling GSettings
  dconf:
    key: "{{ item }}"
    value: "true"
  loop: "{{ gsettings['enable'] }}"

- name: Disabling GSettings
  dconf:
    key: "{{ item }}"
    value: "false"
  loop: "{{ gsettings['disable'] }}"

- name: Setting favorite apps
  dconf:
    key: /org/gnome/shell/favorite-apps
    value: "{{ favorite_apps }}"

- name: Adjusting window button layout
  dconf:
    key: /org/gnome/desktop/wm/preferences/button-layout
    value: "{{ button_layout }}"

- name: Adjusting GNOME privacy settings
  dconf:
    key: "/org/gnome/desktop/privacy/{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ privacy_settings }}"

- name: Enabling GNOME night light
  dconf:
    key: "/org/gnome/settings-daemon/plugins/color/night-light-{{item.key}}"
    value: "{{ item.value }}"
  loop: "{{ night_light }}"

- name: Adjusting power settings
  dconf:
    key: "/org/gnome/{{item.key}}"
    value: "{{ item.value }}"
  loop: "{{ power }}"

- name: Configuring GNOME text editor
  dconf:
    key: "/org/gnome/gedit/preferences/editor/{{ item.key }}"
    value: "{{ item.value }}"
  loop: "{{ gedit_settings }}"
