---
- name: Icon Theme - Numix Circle
  block:
  - name: Install Numix Circle Icon Theme
    dnf:
      name: numix-icon-theme-circle
      state: present
    become: yes

  - name: Set as default Icon Theme
    dconf:
      key: /org/gnome/desktop/interface/icon-theme
      value: "'Numix-Circle'"

  tags:
    - gsettings
