---
keyboard_layout: "[('xkb', 'de')]"

keybindings_default:
  # "Ctrl+Q" to close windows
  - { key: /org/gnome/desktop/wm/keybindings/close, value: "'<Primary>q'" }
  # "Super+D" to show desktop
  - { key: /org/gnome/desktop/wm/keybindings/show-desktop, value: "['<Super>d']" }
  # "Super+F" to open file manager
  - { key: /org/gnome/settings-daemon/plugins/media-keys/home, value: "'<Super>f'" }

keybindings_custom:
  # Keybinding to launch Terminal
  launch_terminal:
    - { key: binding, value: "'<Primary><Alt>t'" }
    - { key: command, value: "'gnome-terminal'" }
    - { key: name, value: "'Launch Terminal'" }
  # Keybinding to launch System Monitor
  launch_system_monitor:
    - { key: binding, value: "'<Primary><Alt>m'" }
    - { key: command, value: "'gnome-system-monitor'" }
    - { key: name, value: "'Launch System Monitor'" }
