---
- name: Podman & Buildah
  block:
    - name: Install Podman & Buildah
      dnf:
        name: "{{ item }}"
        state: present
      loop:
        - podman
        - buildah
      become: yes

    - name: Create Directories for Podman & Buildah Configuration Files
      file:
        path: "{{ oci_conf_path }}"
        state: directory

    - name: Copy Podman & Buildah Configuration Files
      template:
        src: "{{ item }}.j2"
        dest: "{{ oci_conf_path }}/{{ item }}"
      loop:
        - libpod.conf
        - storage.conf
      tags:
        - configuration
