---
vscodium_packages:
  - dbaeumer.vscode-eslint
  # - formulahendry.code-runner
  - ms-python.python
  - redhat.vscode-yaml
  - redhat.vscode-xml
  - timonwong.shellcheck
  - zhuangtongfa.material-theme
