---
- name: Installing PHP & Composer packages
  block:
  - name: Installing PHP & extensions
    apt:
      name: "{{ php_packages }}"
      state: present
    become: true

  - name: Creating directories
    file:
      path:  "{{ composer_packages_path }}"
      state: directory

  - name: Installing Composer packages
    composer:
      command: require
      global_command: yes
      arguments: "{{ item }}"
    loop: "{{ composer_packages }}"

  # - name: Installing Composer packages
  #   command: /usr/bin/composer global require {{ item }}
  #   loop: "{{ composer_packages }}"
  #   register: install_composer_packages
  #   changed_when: '"Nothing to install or update" not in install_composer_packages.stderr'
