---
php_packages:
  - composer
  - imagemagick
  - php-cli
  - php-dev
  - php-bcmath
  - php-curl
  - php-gd
  - php-imagick
  - php-json
  - php-mbstring
  - php-soap
  - php-xml
  - php-yaml
  - php-zip

composer_packages_path: "{{ lib_path }}/php"

composer_packages:
  - friendsofphp/php-cs-fixer
  - phploc/phploc
  - sebastian/phpcpd
  - sensiolabs/security-checker
  - squizlabs/php_codesniffer
