---
- name: Installing Ruby & gems
  block:
    - name: Installing Ruby
      apt:
        name: "{{ ruby_packages }}"
        state: present
      become: true

    - name: Creating directories
      file:
        path: "{{ ruby_gems_path }}"
        state: directory

    - name: Installing local Ruby gems
      gem:
        name: "{{ item }}"
        state: present
      loop: "{{ ruby_gems }}"

  tags:
    - ruby
